// ============================================================
// CONFIG — MEMORY VAULT / ANNIVERSARY 07.10.2022
// Edit bagian nama, tanggal, pesan, dan fase cerita di sini.
// ============================================================
window.KONFIG = {
  namaKamu: "Ramadhan Tri Atmojo",
  namaDia: "Ila Meydina",
  kodeTanggal: "07102022",
  tanggalJadian: "2022-10-07T00:00:00",
  tahunKe: 4,

  pembuka: [
    "Untuk kamu, yang entah kenapa selalu berhasil bikin hari biasa terasa lebih berarti.",
    "Empat tahun lalu, kita mulai dari satu tanggal. Sekarang tanggal itu sudah jadi rumah bagi banyak cerita.",
    "Aku nggak mau bilang semua hari kita sempurna, karena memang nggak begitu.",
    "Tapi dari semua hari yang pernah kita lewati, aku tetap paling bersyukur karena ada kamu di dalamnya.",
    "Jadi malam ini, aku cuma mau mengajak kamu melihat lagi sedikit bagian dari perjalanan kita.",
  ],

  bab: [
    { tahun: "01 / FIRST CHAPTER", judul: "Dari satu tanggal yang sederhana", teks: "07 Oktober 2022. Waktu itu mungkin kita belum tahu bakal sejauh ini. Tapi ternyata, satu tanggal sederhana bisa jadi awal dari begitu banyak cerita.", foto: "assets/foto/memory-001.webp" },
    { tahun: "02 / GROWING", judul: "Pelan-pelan jadi saling tahu", teks: "Kita belajar mengenal hal-hal kecil: cara masing-masing bercanda, cara diam saat capek, sampai hal-hal sepele yang akhirnya justru paling kita ingat.", foto: "assets/foto/memory-027.webp" },
    { tahun: "03 / STAYING", judul: "Bukan selalu mudah, tapi tetap bersama", teks: "Ada hari yang ringan, ada juga yang bikin sama-sama lelah. Tapi justru di sana aku belajar, sayang itu bukan cuma tentang bahagia. Sayang juga tentang tetap tinggal dan memperbaiki.", foto: "assets/foto/memory-061.webp" },
    { tahun: "04 / HOME", judul: "Sekarang, rasanya seperti pulang", teks: "Mungkin itu kenapa keberadaan kamu terasa sederhana tapi besar. Bukan karena semuanya selalu ramai, tapi karena ada rasa tenang ketika tahu kita masih punya satu sama lain.", foto: "assets/foto/memory-088.webp" }
  ],

  alasan: [
    "Karena sama kamu, obrolan receh pun bisa jadi sesuatu yang nanti aku kangenin.",
    "Karena kamu punya cara sendiri untuk bikin aku merasa diperhatikan, bahkan lewat hal-hal kecil.",
    "Karena setelah hari yang panjang, kamu tetap jadi salah satu orang pertama yang pengin aku ceritain semuanya.",
    "Karena waktu kita sama-sama salah, kamu tetap mau ngobrol sampai akhirnya kita ngerti satu sama lain lagi.",
    "Karena banyak momen kecil sama kamu yang kelihatannya biasa, tapi ternyata tinggal lama di kepala aku.",
    "Karena aku nggak cuma sayang sama versi kamu yang sedang bahagia, aku juga peduli sama kamu di hari-hari yang berat.",
    "Karena dari sekian banyak cerita yang bisa aku jalani, cerita sama kamu adalah yang paling ingin aku lanjutkan.",
    "Karena sampai sekarang aku masih penasaran, setelah ini kita akan punya cerita apa lagi?"
  ],

  surat: [
    "Sayang, aku bikin halaman ini bukan karena aku jago ngomong soal perasaan. Justru karena ada beberapa hal yang kalau disimpan terus, rasanya sayang banget kalau nggak pernah disampaikan.",
    "Terima kasih ya. Bukan cuma untuk momen besar yang jelas-jelas kita ingat, tapi juga untuk hal kecil yang mungkin buat kamu sepele. Cara kamu nanya kabar, cara kamu nemenin, cara kamu tetap ada. Hal-hal begitu justru yang diam-diam paling berarti buat aku.",
    "Aku tahu perjalanan kita nggak selalu manis. Kita pernah beda pikiran, pernah capek, pernah sama-sama nggak tahu harus mulai ngomong dari mana. Tapi mungkin justru itu yang bikin semuanya terasa nyata. Kita bukan dua orang yang selalu benar, kita cuma dua orang yang masih mau belajar memahami.",
    "Hari ini, 07 Oktober 2026, kita sudah sampai di tahun keempat. Rasanya cepat banget. Tapi kalau aku lihat semua foto dan video ini, ternyata banyak juga yang sudah kita lewati. Dan anehnya, aku masih pengin nambah lagi.",
    "Jadi terima kasih sudah sampai di sini sama aku. Terima kasih sudah jadi bagian dari hidupku. Semoga nanti, saat kita lihat halaman ini lagi, kita bisa senyum karena ternyata cerita kita sudah jauh lebih panjang dari yang pernah kita bayangkan.",
    "Selamat anniversary, sayang. Aku nggak janji setiap hari akan sempurna. Tapi aku mau tetap jadi orang yang berusaha memilih kamu, lagi dan lagi."
  ],
  suratTtd: "Dengan sayang,",
  kejutan: "Dan kalau suatu hari kamu lupa betapa berartinya kamu buat aku, buka lagi halaman ini. Karena semua yang ada di sini cuma punya satu kesimpulan: aku tetap memilih kamu. ❤️",

  galeri: [
    { id: "p001", foto: "assets/foto/memory-001.webp", tulisan: "" },
    { id: "p002", foto: "assets/foto/memory-002.webp", tulisan: "" },
    { id: "p003", foto: "assets/foto/memory-003.webp", tulisan: "" },
    { id: "p004", foto: "assets/foto/memory-004.webp", tulisan: "" },
    { id: "p005", foto: "assets/foto/memory-005.webp", tulisan: "" },
    { id: "p006", foto: "assets/foto/memory-006.webp", tulisan: "" },
    { id: "p007", foto: "assets/foto/memory-007.webp", tulisan: "" },
    { id: "p008", foto: "assets/foto/memory-008.webp", tulisan: "" },
    { id: "p009", foto: "assets/foto/memory-009.webp", tulisan: "" },
    { id: "p010", foto: "assets/foto/memory-010.webp", tulisan: "" },
    { id: "p011", foto: "assets/foto/memory-011.webp", tulisan: "" },
    { id: "p012", foto: "assets/foto/memory-012.webp", tulisan: "" },
    { id: "p013", foto: "assets/foto/memory-013.webp", tulisan: "" },
    { id: "p014", foto: "assets/foto/memory-014.webp", tulisan: "" },
    { id: "p015", foto: "assets/foto/memory-015.webp", tulisan: "" },
    { id: "p016", foto: "assets/foto/memory-016.webp", tulisan: "" },
    { id: "p017", foto: "assets/foto/memory-017.webp", tulisan: "" },
    { id: "p018", foto: "assets/foto/memory-018.webp", tulisan: "" },
    { id: "p019", foto: "assets/foto/memory-019.webp", tulisan: "" },
    { id: "p020", foto: "assets/foto/memory-020.webp", tulisan: "" },
    { id: "p021", foto: "assets/foto/memory-021.webp", tulisan: "" },
    { id: "p022", foto: "assets/foto/memory-022.webp", tulisan: "" },
    { id: "p023", foto: "assets/foto/memory-023.webp", tulisan: "" },
    { id: "p024", foto: "assets/foto/memory-024.webp", tulisan: "" },
    { id: "p025", foto: "assets/foto/memory-025.webp", tulisan: "" },
    { id: "p026", foto: "assets/foto/memory-026.webp", tulisan: "" },
    { id: "p027", foto: "assets/foto/memory-027.webp", tulisan: "" },
    { id: "p028", foto: "assets/foto/memory-028.webp", tulisan: "" },
    { id: "p029", foto: "assets/foto/memory-029.webp", tulisan: "" },
    { id: "p030", foto: "assets/foto/memory-030.webp", tulisan: "" },
    { id: "p031", foto: "assets/foto/memory-031.webp", tulisan: "" },
    { id: "p032", foto: "assets/foto/memory-032.webp", tulisan: "" },
    { id: "p033", foto: "assets/foto/memory-033.webp", tulisan: "" },
    { id: "p034", foto: "assets/foto/memory-034.webp", tulisan: "" },
    { id: "p035", foto: "assets/foto/memory-035.webp", tulisan: "" },
    { id: "p036", foto: "assets/foto/memory-036.webp", tulisan: "" },
    { id: "p037", foto: "assets/foto/memory-037.webp", tulisan: "" },
    { id: "p038", foto: "assets/foto/memory-038.webp", tulisan: "" },
    { id: "p039", foto: "assets/foto/memory-039.webp", tulisan: "" },
    { id: "p040", foto: "assets/foto/memory-040.webp", tulisan: "" },
    { id: "p041", foto: "assets/foto/memory-041.webp", tulisan: "" },
    { id: "p042", foto: "assets/foto/memory-042.webp", tulisan: "" },
    { id: "p043", foto: "assets/foto/memory-043.webp", tulisan: "" },
    { id: "p044", foto: "assets/foto/memory-044.webp", tulisan: "" },
    { id: "p045", foto: "assets/foto/memory-045.webp", tulisan: "" },
    { id: "p046", foto: "assets/foto/memory-046.webp", tulisan: "" },
    { id: "p047", foto: "assets/foto/memory-047.webp", tulisan: "" },
    { id: "p048", foto: "assets/foto/memory-048.webp", tulisan: "" },
    { id: "p049", foto: "assets/foto/memory-049.webp", tulisan: "" },
    { id: "p050", foto: "assets/foto/memory-050.webp", tulisan: "" },
    { id: "p051", foto: "assets/foto/memory-051.webp", tulisan: "" },
    { id: "p052", foto: "assets/foto/memory-052.webp", tulisan: "" },
    { id: "p053", foto: "assets/foto/memory-053.webp", tulisan: "" },
    { id: "p054", foto: "assets/foto/memory-054.webp", tulisan: "" },
    { id: "p055", foto: "assets/foto/memory-055.webp", tulisan: "" },
    { id: "p056", foto: "assets/foto/memory-056.webp", tulisan: "" },
    { id: "p057", foto: "assets/foto/memory-057.webp", tulisan: "" },
    { id: "p058", foto: "assets/foto/memory-058.webp", tulisan: "" },
    { id: "p059", foto: "assets/foto/memory-059.webp", tulisan: "" },
    { id: "p060", foto: "assets/foto/memory-060.webp", tulisan: "" },
    { id: "p061", foto: "assets/foto/memory-061.webp", tulisan: "" },
    { id: "p062", foto: "assets/foto/memory-062.webp", tulisan: "" },
    { id: "p063", foto: "assets/foto/memory-063.webp", tulisan: "" },
    { id: "p064", foto: "assets/foto/memory-064.webp", tulisan: "" },
    { id: "p065", foto: "assets/foto/memory-065.webp", tulisan: "" },
    { id: "p066", foto: "assets/foto/memory-066.webp", tulisan: "" },
    { id: "p067", foto: "assets/foto/memory-067.webp", tulisan: "" },
    { id: "p068", foto: "assets/foto/memory-068.webp", tulisan: "" },
    { id: "p069", foto: "assets/foto/memory-069.webp", tulisan: "" },
    { id: "p070", foto: "assets/foto/memory-070.webp", tulisan: "" },
    { id: "p071", foto: "assets/foto/memory-071.webp", tulisan: "" },
    { id: "p072", foto: "assets/foto/memory-072.webp", tulisan: "" },
    { id: "p073", foto: "assets/foto/memory-073.webp", tulisan: "" },
    { id: "p074", foto: "assets/foto/memory-074.webp", tulisan: "" },
    { id: "p075", foto: "assets/foto/memory-075.webp", tulisan: "" },
    { id: "p076", foto: "assets/foto/memory-076.webp", tulisan: "" },
    { id: "p077", foto: "assets/foto/memory-077.webp", tulisan: "" },
    { id: "p078", foto: "assets/foto/memory-078.webp", tulisan: "" },
    { id: "p079", foto: "assets/foto/memory-079.webp", tulisan: "" },
    { id: "p080", foto: "assets/foto/memory-080.webp", tulisan: "" },
    { id: "p081", foto: "assets/foto/memory-081.webp", tulisan: "" },
    { id: "p082", foto: "assets/foto/memory-082.webp", tulisan: "" },
    { id: "p083", foto: "assets/foto/memory-083.webp", tulisan: "" },
    { id: "p084", foto: "assets/foto/memory-084.webp", tulisan: "" },
    { id: "p085", foto: "assets/foto/memory-085.webp", tulisan: "" },
    { id: "p086", foto: "assets/foto/memory-086.webp", tulisan: "" },
    { id: "p087", foto: "assets/foto/memory-087.webp", tulisan: "" },
    { id: "p088", foto: "assets/foto/memory-088.webp", tulisan: "" },
    { id: "p089", foto: "assets/foto/memory-089.webp", tulisan: "" },
    { id: "p090", foto: "assets/foto/memory-090.webp", tulisan: "" },
    { id: "p091", foto: "assets/foto/memory-091.webp", tulisan: "" },
    { id: "p092", foto: "assets/foto/memory-092.webp", tulisan: "" },
    { id: "p093", foto: "assets/foto/memory-093.webp", tulisan: "" },
    { id: "p094", foto: "assets/foto/memory-094.webp", tulisan: "" },
    { id: "p095", foto: "assets/foto/memory-095.webp", tulisan: "" },
    { id: "p096", foto: "assets/foto/memory-096.webp", tulisan: "" },
    { id: "p097", foto: "assets/foto/memory-097.webp", tulisan: "" },
    { id: "p098", foto: "assets/foto/memory-098.webp", tulisan: "" }
  ],

  video: [
    { id: "v001", file: "assets/video/film-01.mp4", poster: "assets/poster/film-01.jpg", judul: "Satu potongan yang ingin disimpan" },
    { id: "v002", file: "assets/video/film-02.mp4", poster: "assets/poster/film-02.jpg", judul: "Satu lagi untuk diingat" }
  ],

  musikDefault: {
  file: "assets/music/My Heart (Lirik) ~Acha & Irwansyah.mp3",
  judul: "My Heart (Lirik) ~Acha & Irwansyah",
  info: "Lagu yang menemani cerita Ramadhan dan Ila."
}
};
